# Generated by Django 5.0.3 on 2024-05-26 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_email_profile_user_alter_profile_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=50)),
                ('orientation', models.CharField(choices='', max_length=50)),
                ('smoker', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
