# Generated by Django 5.0.3 on 2024-05-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_message_recipient_profilemessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datingprofile',
            name='orientation',
        ),
    ]
