# Generated by Django 5.0.3 on 2024-05-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_message_recipient_delete_profilemessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datingprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datingprofile',
            name='interested_in',
            field=models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('both', 'BOTH')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datingprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datingprofile',
            name='smoker',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=50, null=True),
        ),
    ]
