# Generated by Django 5.0.3 on 2024-05-27 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_datingprofile_age_datingprofile_interested_in_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="datingprofile",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dating_profile_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personality_profile_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datingprofile",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="are_you_active",
            field=models.CharField(
                choices=[("1", "YES"), ("1", "NO")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="do_you_like_drinking",
            field=models.CharField(
                choices=[("1", "YES"), ("1", "NO")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="interests",
            field=models.CharField(
                choices=[
                    ("1", "Long-term partner"),
                    ("2", "Short-term partner"),
                    ("3", "Still figuring out"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="movie_pick",
            field=models.CharField(
                choices=[
                    ("1", "HORROR"),
                    ("2", "ROMANCE"),
                    ("3", "COMEDY"),
                    ("4", "ACTION"),
                    ("5", "ANIME"),
                    ("6", "SCI-FI"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="music_pick",
            field=models.CharField(
                choices=[
                    ("1", "METAL"),
                    ("2", "CLASSIC"),
                    ("3", "COUNTRY"),
                    ("4", "POP"),
                    ("5", "HIP-HOP"),
                    ("6", "GOSPEL"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="outdoor_indoor_pick",
            field=models.CharField(
                choices=[("1", "OUTDOOR"), ("2", "INDOOR")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="what_do_you_do_for_fun_pick",
            field=models.CharField(
                choices=[
                    ("1", "HIKING"),
                    ("2", "GAMING"),
                    ("3", "Reading"),
                    ("4", "SINGING"),
                    ("5", "SPORTS"),
                    ("6", "DANCING"),
                    ("7", "TRAVEL"),
                    ("8", "POETRY"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="gender",
            field=models.CharField(
                choices=[("1", "MALE"), ("2", "FEMALE")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="interested_in",
            field=models.CharField(
                choices=[("1", "MEN"), ("2", "WOMEN"), ("3", "BOTH")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="smoker",
            field=models.CharField(
                choices=[("1", "YES"), ("2", "NO")], max_length=50, null=True
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
