# Generated by Django 5.0.3 on 2024-05-28 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_userprofile_alter_datingprofile_user_profile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="is_special",
            new_name="has_profile",
        ),
    ]
