# Generated by Django 5.0.3 on 2024-05-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_datingprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datingprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "MALE"), ("Female", "FEMALE")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="interested_in",
            field=models.CharField(
                choices=[("Men", "MEN"), ("Women", "WOMEN"), ("Both", "BOTH")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datingprofile",
            name="smoker",
            field=models.CharField(
                choices=[("Yes", "YES"), ("No", "NO")], max_length=50, null=True
            ),
        ),
    ]
