# Generated by Django 5.0.3 on 2024-05-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_datingprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datingprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "MALE"), ("Female", "FEMALE")],
                max_length=50,
                null=True,
            ),
        ),
    ]
