# Generated by Django 5.0.3 on 2024-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_alter_datingprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="datingprofile",
            name="created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="created",
            field=models.BooleanField(default=False),
        ),
    ]
