# Generated by Django 5.0.3 on 2024-05-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_datingprofile_created_personalityprofile_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalityprofile",
            name="are_you_active",
            field=models.CharField(
                choices=[("Yes", "YES"), ("No", "NO")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="do_you_like_drinking",
            field=models.CharField(
                choices=[("Yes", "YES"), ("No", "NO")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="interests",
            field=models.CharField(
                choices=[
                    ("long-term", "Long-term partner"),
                    ("short-term", "Short-term partner"),
                    ("firguring-out", "Still figuring out"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="movie_pick",
            field=models.CharField(
                choices=[
                    ("horror", "HORROR"),
                    ("romance", "ROMANCE"),
                    ("comedy", "COMEDY"),
                    ("action", "ACTION"),
                    ("anime", "ANIME"),
                    ("sci-fi", "SCI-FI"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="music_pick",
            field=models.CharField(
                choices=[
                    ("metal", "METAL"),
                    ("classic", "CLASSIC"),
                    ("country", "COUNTRY"),
                    ("pop", "POP"),
                    ("hip-hop", "HIP-HOP"),
                    ("gospel", "GOSPEL"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="outdoor_indoor_pick",
            field=models.CharField(
                choices=[("outdoor", "OUTDOOR"), ("indoor", "INDOOR")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dating_profile_user",
                to="app.datingprofile",
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="what_do_you_do_for_fun_pick",
            field=models.CharField(
                choices=[
                    ("hiking", "HIKING"),
                    ("gaming", "GAMING"),
                    ("reading", "Reading"),
                    ("singing", "SINGING"),
                    ("sport", "SPORTS"),
                    ("dancing", "DANCING"),
                    ("travel", "TRAVEL"),
                    ("poetry", "POETRY"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
