# Generated by Django 5.0.3 on 2024-05-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datingprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="no-profile-picture-icon-15_oLIFS4i.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
