# Generated by Django 5.0.3 on 2024-05-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_datingprofile_occupation"),
    ]

    operations = [
        migrations.AddField(
            model_name="datingprofile",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="datingprofile",
            name="drinker",
            field=models.CharField(
                choices=[("Yes", "YES"), ("No", "NO")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="datingprofile",
            name="favorite_place_ever_been",
            field=models.TextField(null=True),
        ),
    ]
