# Generated by Django 5.0.3 on 2024-05-29 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_datingprofile_bio_datingprofile_drinker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="has_dating_profile",
        ),
    ]
