# Generated by Django 5.0.3 on 2024-05-29 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_remove_profile_has_dating_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="parent_message",
        ),
        migrations.RemoveField(
            model_name="message",
            name="received_date",
        ),
        migrations.RemoveField(
            model_name="message",
            name="status",
        ),
    ]
