# Generated by Django 5.0.3 on 2024-05-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_message_content_message_parent_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalityprofile",
            name="hobby_pick",
            field=models.CharField(
                choices=[
                    ("biking", "BIKING"),
                    ("knitting", "KNITTING"),
                    ("painting", "PAINTING"),
                    ("bird-watching", "BIRD-WATCHING"),
                    ("antiquing", "ANTIQUING"),
                    ("couch-potato", "COUCH-POTATO"),
                    ("kayaking", "KAYAKING"),
                    ("swimming", "SWIMMING"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personalityprofile",
            name="sport_pick",
            field=models.CharField(
                choices=[
                    ("baseball", "BASEBALL"),
                    ("basketball", "BASKETBALL"),
                    ("tennis", "TENNIS"),
                    ("football", "FOOTBALL"),
                    ("soccer", "SOCCER"),
                    ("skate", "SKATING"),
                    ("golf", "GOLF"),
                ],
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="what_do_you_do_for_fun_pick",
            field=models.CharField(
                choices=[
                    ("hiking", "HIKING"),
                    ("gaming", "GAMING"),
                    ("reading", "READING"),
                    ("singing", "SINGING"),
                    ("sports", "SPORTS"),
                    ("dancing", "DANCING"),
                    ("travel", "TRAVEL"),
                    ("poetry", "POETRY"),
                    ("music", "MUSIC"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
