# Generated by Django 5.0.3 on 2024-05-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_personalityprofile_hobby_pick_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datingprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default_profile.png", null=True, upload_to=""
            ),
        ),
    ]
