# Generated by Django 5.0.3 on 2024-06-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_alter_personalityprofile_what_do_you_do_for_fun_pick"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datingprofile",
            name="age",
        ),
        migrations.AddField(
            model_name="datingprofile",
            name="birth_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="personalityprofile",
            name="what_do_you_do_for_fun_pick",
            field=models.CharField(
                choices=[
                    ("Hiking", "HIKING"),
                    ("Gaming", "GAMING"),
                    ("Reading", "READING"),
                    ("Singing", "SINGING"),
                    ("Sports", "SPORTS"),
                    ("Dancing", "DANCING"),
                    ("Travel", "TRAVEL"),
                    ("Poetry", "POETRY"),
                    ("Music", "MUSIC"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
